### ISSUE TITLE
跨平台编译错误

### ISSUE THREAD

**Issue by wangqinyu** [NervJS/taro-ui#362] opened 2019-01-18 09:00 UTC
**问题描述**
使用taro编写了一个小程序，使用了taro-ui，在Linux和mac平台编译和使用都正常，同样的代码在windows上编译的小程序出现问题，问题主要出现在：当点击菜单的时候，控制台报错。

**复现步骤**
[复现问题的步骤]
1. 在菜单上面点击切换

[或者可以直接贴源代码，能贴文字就不要截图]

```js
render() {
    let currentView = null
    let tab = this.state.tabList[this.state.currentTab] || {}
    if (tab.id === 'projects') {
      currentView = (<ProjectList></ProjectList>)
    } else if (tab.id === 'tasks') {
      currentView = <TaskList />
    } else if (tab.id === 'me') {
      currentView = <More></More>
    }

    return (
      <View className='index' >
        {currentView}
        <AtTabBar fixed tabList={this.state.tabList}
          onClick={this.handleSwitchTabs}
          current={this.state.currentTab}
        />
      </View >
    )
  }

```

**期望行为**
期望页面根据菜单点击进行切换
**报错信息**

错误如下：

`webviewScriptError
Cannot read property 'offsetLeft' of undefined;[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
TypeError: Cannot read property 'offsetLeft' of undefined
    at v (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:20:3894)
    at r.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:20:5014)
    at o.safeCallback (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:11511)
    at o.call (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:11275)
    at n (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:13741)
    at http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:14295
    at s (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:13309)
    at Function.o.dispatchEvent (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:14196)
    at t (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:7:9572)
    at g (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:7:10057)
[Exparser] [Error] [Component] Event Listener Error @ wx-view#(anonymous)
(anonymous) @ VM1015:5
TypeError: Cannot read property 'offsetLeft' of undefined
    at v (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:20:3894)
    at r.t.(anonymous function).(anonymous function).t.addListener.capture (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:20:5014)
    at o.safeCallback (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:11511)
    at o.call (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:11275)
    at n (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:13741)
    at http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:14295
    at s (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:13309)
    at Function.o.dispatchEvent (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:5:14196)
    at t (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:7:9572)
    at g (http://127.0.0.1:63644/__pageframe__/__dev__/WAWebview.js:7:10057)`

**系统信息**
> Taro v1.2 及以上版本已添加 `taro info` 命令，方便大家查看系统及依赖信息，运行该命令后将结果贴下面即可。

 - Taro 版本 [e.g. v.1.2.3]
 - Taro UI 版本 [e.g. v.1.3.1]
 - 报错平台 [weapp]

**补充信息**
[可选]
[根据你的调查研究，出现这个问题的原因可能在哪里？]

**Comment by koppthe** [comment] 2019-01-18 09:12
Duplicate of #357

**Comment by koppthe** [comment] 2019-01-22 12:40
微信开发者工具的基础库版本是多少？ taro 和 taro-ui 的版本都升级到最新版本试试？

**Closed** 2019-02-21 13:53 UTC
Labels: invalid
